### ISSUE TITLE
Debtor checkLogin is a protected function

### ISSUE THREAD

**Issue by casdr** [hyperized/wefact#5]
https://github.com/hyperized/wefact/blob/master/src/Types/Debtor.php#L27

Is this a protected function with a reason or is this an error?

**Comment by hyperized** [comment]
It sure is! I'll get a fix out shortly.

**Comment by hyperized** [comment]
https://github.com/hyperized/wefact/releases/tag/v2.3.3 fixed the issue. Thanks!

**Comment by casdr** [comment]
You forgot checkLogin on Debtor :)

Thanks!

**Comment by hyperized** [comment]
Ugh, hold on :D.

**Comment by hyperized** [comment]
Could you verify please :)?

**Comment by casdr** [comment]
Haha, it's correct now. Thanks!
